#!/bin/bash
#                                         AUTHOR: KEMDJO MOTSEBO
#                                           DATE: June 2022
# This script performs a full system inventory and provides a file that contains the inventory report.

# ########################################## System inventory ###############################################

echo "Welcome to the full system inventory Please wait, we are working"
sleep 5
echo "Please enter your system inventory file name"
read name

touch /home/$(whoami)/${name}

echo "    #################################################
$(date)" >> /home/$(whoami)/${name}

echo "    ##################################################
CPU INVENTORY" >> /home/$(whoami)/${name}
lscu >> /home/$(whoami)/${name}

echo "    ###################################################
MEMORY INVENTORY" >> /home/$(whoami)/${name}
free -m >> /home/$(whoami)/${name}

echo "    ###################################################
HARD DRIVE INVENTORY" >> /home/$(whoami)/${name}
lsblk >> /home/$(whoami)/${name}

echo "    ####################################################
OS-INVENTORY" >> /home/$(whoami)/${name}
cat /etc/os-release >> /home/$(whoami)/${name}

echo "    #####################################################
KERNEL INVENTORY" >> /home/$(whoami)/${name}
uname -m >> /home/$(whoami)/${name}

echo "    ######################################################
END OF INVENTORY - THANK YOU!" >> /home/$(whoami)/${name}
clear

echo "Your system inventory file named - ${name} - is ready and can be found in /home/$(whoami) directory"
